
export const seedTutors = [
  {
    tutorName: "Dr. Sarah Johnson",
    photoURL: "https://i.ibb.co.com/Z6Q6RJds/photo-1544005313-94ddf0286df2.jpg",
    subject: "Mathematics",
    availableDays: "Sun - Thu",
    availableTimeSlot: "5:00 PM - 8:00 PM",
    hourlyFee: 40,
    totalSlot: 12,
    sessionStartDate: "2026-06-05",
    institution: "Harvard University",
    experience: "8 Years",
    location: "New York",
    teachingMode: "Online",
    userEmail: "default@mediqueue.com",
  },

  {
    tutorName: "Prof. Michael Brown",
    photoURL: "https://i.ibb.co.com/gM0yfzts/photo-1506794778202-cad84cf45f1d.jpg",
    subject: "Physics",
    availableDays: "Sat - Wed",
    availableTimeSlot: "6:00 PM - 9:00 PM",
    hourlyFee: 50,
    totalSlot: 10,
    sessionStartDate: "2026-05-08",
    institution: "Stanford University",
    experience: "10 Years",
    location: "California",
    teachingMode: "Both",
    userEmail: "default@mediqueue.com",
  },

  {
    tutorName: "Emily Davis",
    photoURL: "https://i.ibb.co.com/mrmQvNQZ/photo-1494790108377-be9c29b29330.jpg",
    subject: "Chemistry",
    availableDays: "Sun - Tue",
    availableTimeSlot: "4:00 PM - 7:00 PM",
    hourlyFee: 35,
    totalSlot: 8,
    sessionStartDate: "2026-03-10",
    institution: "University of Oxford",
    experience: "6 Years",
    location: "London",
    teachingMode: "Offline",
    userEmail: "default@mediqueue.com",
  },

  {
    tutorName: "James Wilson",
    photoURL: "https://i.ibb.co.com/00QxrPc/photo-1500648767791-00dcc994a43e.jpg",
    subject: "Biology",
    availableDays: "Mon - Thu",
    availableTimeSlot: "3:00 PM - 6:00 PM",
    hourlyFee: 45,
    totalSlot: 15,
    sessionStartDate: "2026-01-12",
    institution: "University of Toronto",
    experience: "9 Years",
    location: "Toronto",
    teachingMode: "Both",
    userEmail: "default@mediqueue.com",
  },

  {
    tutorName: "Sophia Martinez",
    photoURL: "https://i.ibb.co.com/BJdpcRV/photo-1438761681033-6461ffad8d80.jpg",
    subject: "English",
    availableDays: "Sun - Fri",
    availableTimeSlot: "7:00 PM - 10:00 PM",
    hourlyFee: 30,
    totalSlot: 20,
    sessionStartDate: "2026-04-15",
    institution: "University of Melbourne",
    experience: "7 Years",
    location: "Melbourne",
    teachingMode: "Online",
    userEmail: "default@mediqueue.com",
  },

  {
    tutorName: "David Anderson",
    photoURL: "https://i.ibb.co.com/BVWH4x2v/photo-1504593811423-6dd665756598.jpg",
    subject: "Computer Science",
    availableDays: "Sat - Thu",
    availableTimeSlot: "8:00 PM - 10:00 PM",
    hourlyFee: 60,
    totalSlot: 18,
    sessionStartDate: "2026-06-18",
    institution: "Massachusetts Institute of Technology",
    experience: "12 Years",
    location: "Boston",
    teachingMode: "Online",
    userEmail: "default@mediqueue.com",
  },
];